apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-frontend
  labels:
    app: fraud-detection-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection-frontend
  template:
    metadata:
      labels:
        app: fraud-detection-frontend
    spec:
      containers:
        - name: fraud-detection-frontend
          image: fraud-detection-frontend
          envFrom:
          - configMapRef:
              name: fraud-detection-frontend-config
          # env:
          # #     - name: API_URL
          # #       value: churn-api.default.svc
          # - name: API_URL
          #   valueFrom:
          #     configMapKeyRef:
          #       name: fraud-detection-frontend-config
          #       key: API_URL
          ports:
            - containerPort: 8501
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 5000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 5000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
      #     volumeMounts:
      #       - name: model-volume
      #         mountPath: /app/nn_model.joblib
      #         subPath: nn_model.joblib
      # volumes:
      #   - name: model-volume
      #     configMap:
      #       name: model-configmap
