apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-frontend
  labels:
    app: fraud-detection-frontend
spec:
  type: ClusterIP
  ports:
    - port: 8501
      targetPort: 8501
  selector:
    app: fraud-detection-frontend
