apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fraud-detection-frontend-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: fraud-detection-frontend
            port:
              number: 8501
