apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-api
  labels:
    app: fraud-detection-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection-api
  template:
    metadata:
      labels:
        app: fraud-detection-api
    spec:
      containers:
        - name: fraud-detection-api
          image: fraud-detection-api
          envFrom:
          - configMapRef:
              name: fraud-detection-api-config
          # env:
          #   - name: UVICORN_HOST
          #     value: "0.0.0.0"
          #   - name: UVICORN_PORT
          #     value: "8000"
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 5000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 5000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
      #     volumeMounts:
      #       - name: model-volume
      #         mountPath: /app/nn_model.joblib
      #         subPath: nn_model.joblib
      # volumes:
      #   - name: model-volume
      #     configMap:
      #       name: model-configmap
