apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-api
  labels:
    app: fraud-detection-api
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
  selector:
    app: fraud-detection-api
