apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
- ../../base
# - ingress.yaml

configMapGenerator:
- literals:
  - MODEL_FILE=models/best_model.pkl
  name: fraud-detection-api-config

images:
- name: fraud-detection-api
  newName: shivamkurtarkar/fraud-detection-api
  newTag: 1dccc02
